### ISSUE TITLE
Compile `pleco` with stable Rust

### ISSUE THREAD

**Issue by sfleischman105** [sfleischman105/Pleco#76]
The following features need to be stabilized before `pleco` can compile on stable:

- [ ] const_fn ([rust-lang/rust#24111](https://github.com/rust-lang/rust/issues/24111))
- [x] const_indexing  ([rust-lang/rust#29947](https://github.com/rust-lang/rust/issues/29947))
- [ ] trusted_len ([rust-lang/rust#37572](https://github.com/rust-lang/rust/issues/37572))
- [ ] integer_atomics  ([rust-lang/rust#32976](https://github.com/rust-lang/rust/issues/32976))
- [ ] allocator_api ([rust-lang/rust#32838](https://github.com/rust-lang/rust/issues/32838))
- [ ] cfg_target_feature
- [ ] target_feature
- [ ] stdsimd
- [ ] fused

For benchmarking:
- [x] test  (Switched to Criterion with #92 )

Dependency stabilization
- [ ] lazy_static nightly (no current tracking issue)

**Comment by sfleischman105** [comment]
Note, we should replace the use of `core_intrinsics` with something that will stabilize.

**Comment by sfleischman105** [comment]
This should be closed with the next release of pleco, `0.5.0`.

**Comment by sfleischman105** [comment]
Fixed with PR #121, And pushed released with version #123 .
