### ISSUE TITLE
Compile `pleco_engine` with stable Rust

### ISSUE THREAD

**Issue by sfleischman105** [sfleischman105/Pleco#77]
The following features need to be stabilized before pleco_engine can compile on stable:

- [ ] const_fn ([rust-lang/rust#24111](https://github.com/rust-lang/rust/issues/24111))
- [x] const_indexing  ([rust-lang/rust#29947](https://github.com/rust-lang/rust/issues/29947))
- [ ] fused  ([rust-lang/rust#35602](https://github.com/rust-lang/rust/issues/35602))
- [ ] integer_atomics  ([rust-lang/rust#32976](https://github.com/rust-lang/rust/issues/32976))
- [ ] allocator_api ([rust-lang/rust#32838](https://github.com/rust-lang/rust/issues/32838))
- [ ] trusted_len ([rust-lang/rust#32838](https://github.com/rust-lang/rust/issues/37572))
- [ ] ptr_internals

For benchmarking:
- [x] test  (Switched to Criterion with #92 )

Dependency stabilization
- [ ] lazy_static nightly (no current tracking issue)
- [ ] `pleco` needs to be usable on stable as defined by #76 .

**Comment by looak** [comment]
```error[E0554]: #![feature] may not be used on the stable release channel
  --> C:\Users\alexa\.cargo\registry\src\github.com-1ecc6299db9ec823\prefetch-0.2.0\src\lib.rs:18:1
   |
18 | #![feature(link_llvm_intrinsics)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error```

So what version or branch of rust should one be using?

**Comment by sfleischman105** [comment]
@looak currently, nightly rust is required to use `pleco`. I'll double check though to make sure it still compiles on nightly.
